### PR TITLE
feat(RHIDP-2305): switch framework to RHDH v1.2

### PR DESCRIPTION
**Pull request by pmacik**
Followup to #47.

Switches Helm and OLM sources to RHDH v1.2

### CODE REVIEW

**Comment by pmacik** [comment]
Verified by:
* [mvp-helm](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/redhat-performance_backstage-performance/49/pull-ci-redhat-performance-backstage-performance-main-mvp-helm/1801522460365950976)
* [mvp-olm](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/redhat-performance_backstage-performance/49/pull-ci-redhat-performance-backstage-performance-main-mvp-olm/1801522460412088320)

**Review by jhutar — APPROVED** [review]
/lgtm

**Pull request merged**
