### PR TITLE
feat(RHIDP-857): Add scalability test

### PR DESCRIPTION
**Pull request by pmacik**

### CODE REVIEW

**Comment by pmacik** [comment]
Tested and verified by:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/46836/rehearse-46836-pull-ci-redhat-performance-backstage-performance-main-search-catalog-scalability/1735661663161421824

(https://github.com/openshift/release/pull/46836)

**Comment by pmacik** [comment]
/hold testing with following jobs as part of https://github.com/openshift/release/pull/46836
* https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/46836/rehearse-46836-pull-ci-redhat-performance-backstage-performance-main-search-catalog/1737622682481987584
* https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/46836/rehearse-46836-pull-ci-redhat-performance-backstage-performance-main-list-catalog-scalability/1737622447949090816

**Review by jhutar — APPROVED** [review]
/lgtm

**Review by yogananth-subramanian — COMMENTED** [review]
/lgtm

**Pull request merged**
